# Generated by Django 4.0.4 on 2022-06-11 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('Decision Tree', 'Decision Tree'), ('AdaBoost', 'AdaBoost'), ('Multi-Layer Perceptron', 'Multi-Layer Perceptron'), ('Support Vector Machine', 'Support Vector Machine'), ('Random Forest', 'Random Forest'), ('Logistic Regression', 'Logistic Regression')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('result', models.BooleanField()),
                ('vector', models.CharField(max_length=500, null=True)),
                ('filename', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.file')),
                ('model_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.models')),
            ],
        ),
    ]
