# Generated by Django 4.0.4 on 2022-06-11 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_file_uploaded_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='ModelFile',
        ),
    ]
